[project]
name = "eat-and-see"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Linh An", email = "linhan1347@gmail.com" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
eat-and-see = "eat_and_see:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
